export const posterAuthors: Readonly<Record<string, string>> = {
  PP011: "Jaasminerjiith Kaur",
  PP013: "Hasseri Halim",
  PP026: "Nur Aqilah Nadhirah Affendie",
  PP063: "Muhammad Nabil Zaki",
  PP073: "Norodiyah Othman",
  PP074: "Nur Alya Amirah Azhar",
  PP087: "Nurin Arisya Zulazhar",
  PP091: "Nur’Alin Syahmina Hashim",
  PP092: "Muhamad Kamal Zakaria",
  PP099: "Muaz Zikry Mohd Lizam",
  PP101: "Indri Yuliani Hamdani",
  PP102: "Afiqah Mohammad",
  PP107: "Farhan Matloob Khan",
  PP109: "Nur Asyiera Amiruddin",
  PP112: "Widhya Aligita",
  PP116: "Khairunisa Qomariyanti",
  PP120: "Maziana Mahamood",
  PP123: "Zafirah Liyana Abdullah",
  PP126: "Nurul Fatin Athirah Azman",
  PP030: "Mohd Radzi Ab. Aziz",
  PP106: "Larasati Arrum Kusumawardani",
  PP110: "Hanis Hanum Zulkifly",
  PP114: "Ahmed Alaa Al-Temimi",
  PP117: "Nur Ain Shafiqah Binti Mohd Zuki",
  PP119: "Siti Aisyah binti Mohd Nasir",
  PP122: "Ezlina Usir",
  PP125: "Mohammad Suhaidi Sha’ari",
  PP012: "Krupavaram. B",
  PP018: "Jian Yan Chua",
  PP020: "Jun Hao Chiew",
  PP052: "Takuto Niino",
  PP053: "Reiji Negoya",
  PP121: "Ahmad Azani Othman",
  PP015: "Saidatul Akhmal Khairuddin",
  PP041: "Nor Adila Binti Zulkifli",
  PP042: "Nurin Irdina Jamsari Bachtiar",
  PP043: "Mohammad Amirul Izzan Amran",
  PP124: "Nurfarhana Ferdaos",
  PP027: "Syarifah Nur Adriana Syed Abdullah",
  PP031: "Syarifah Nur Adriana Syed Abdullah",
  PP034: "Maureen Canda-Borcelas",
  PP051: "Nur Amirah Khirul Anuar",
  PP058: "Ahmad Bazli bin Ahmad Zikrileh",
  PP071: "Nor Sumayah Khalid",
  PP072: "Siti Khadijah Binti Mohammad Fawzi",
  PP085: "Asfarina Amir Hassan",
  PP044: "Sarah Saiful Rizal",
  PP016: "Norfahmi Mohd Yusof",
  PP032: "Erma Wany Abdul Basit",
  PP104: "Nik Shamsiah Nik Salleh",
  PP113: "Nur Sakinah Saifuddin",
  PP118: "Wan Nur Najihah Wan Zulkifli",
  PP127: "Nadia Jalaludin",
  PP128: "Maisarah Roslan",
};
